In [2]:
import numpy as np

In [3]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
mylist

[1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
# одномерный массив
myarr = np.array(mylist)
myarr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
# двумерный массив
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# верхняя граница np.arange не включается в вывод
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones (5)

array([1., 1., 1., 1., 1.])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [18]:
len(np.linspace(0,10,11))

11

In [20]:
len(np.linspace(0,10,21))

21

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(1)

array([0.23205255])

In [29]:
np.random.rand(5,2)

array([[0.37129907, 0.17924305],
       [0.25700515, 0.42647627],
       [0.65490025, 0.43927946],
       [0.20701747, 0.08351368],
       [0.35188874, 0.66548711]])

In [31]:
# нормальное распределение (распределение Гаусса):
# Cтандартное нормальное распределение в котором математическое ожидание равно нулю, 
# а дисперcия равно 1
np.random.randn(10)

array([ 0.51875047, -0.09811241, -0.59607487, -0.68875021, -1.01042008,
        0.65371495,  0.03504767,  0.52543402,  1.0619922 ,  0.72307667])

In [44]:
np.random.randn(2,3)

array([[ 1.32786105,  0.87205826,  0.83888595],
       [-0.46809185, -0.83554523, -0.06314008]])

In [48]:
# целые случайные числа
np.random.randint(2, high=101, size=5)

array([96, 73, 73, 17, 70])

In [38]:
np.random.randint(2, high=101, size=(4, 5))

array([[31, 68, 13, 26, 39],
       [11, 68, 59, 93, 28],
       [48,  2, 37, 61,  6],
       [38, 12, 82, 61, 99]])