In [2]:
import numpy as np

In [3]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
mylist

[1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
# одномерный массив
myarr = np.array(mylist)
myarr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
# двумерный массив
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# верхняя граница np.arange не включается в вывод
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones (5)

array([1., 1., 1., 1., 1.])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [18]:
len(np.linspace(0,10,11))

11

In [20]:
len(np.linspace(0,10,21))

21

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(1)

array([0.23205255])

In [28]:
np.random.rand(5,6)

array([[0.22406312, 0.49511811, 0.57315814, 0.51737817, 0.77173428,
        0.98726145],
       [0.49546314, 0.07652562, 0.76229496, 0.0730978 , 0.2893624 ,
        0.70456352],
       [0.16434695, 0.28495253, 0.77452579, 0.94271322, 0.36274689,
        0.8220076 ],
       [0.1982132 , 0.38930805, 0.48779323, 0.3646643 , 0.8691431 ,
        0.67484099],
       [0.54210738, 0.31740133, 0.60778348, 0.21238163, 0.19508373,
        0.50237215]])