In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [9]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [10]:
arr[:5]

array([0, 1, 2, 3, 4])

In [12]:
arr[7:]

array([ 7,  8,  9, 10])

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# присвоить выбранному диапазон другое значение
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])