In [2]:
import numpy as np

In [3]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
mylist

[1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
# одномерный массив
myarr = np.array(mylist)
myarr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
# двумерный массив
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# верхняя граница np.arange не включается в вывод
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones (5)

array([1., 1., 1., 1., 1.])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [18]:
len(np.linspace(0,10,11))

11

In [20]:
len(np.linspace(0,10,21))

21

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])