In [36]:
import numpy as np

In [37]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[8]

8

In [39]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [40]:
arr[:5]

array([0, 1, 2, 3, 4])

In [41]:
arr[7:]

array([ 7,  8,  9, 10])

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# присвоить выбранному диапазонy другое значение
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [44]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:

# создаются НЕ копии массива arr, а ссылки на исходный массив
slice_of_array = arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [46]:
slice_of_array[:5] = 99
slice_of_array

array([99, 99, 99, 99, 99])

In [49]:
new_arr = np.arange(0,10)

In [50]:
new_arr_copy = new_arr.copy()
new_arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
slice_of_new_arr_copy = new_arr_copy.copy()
slice_of_new_arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
slice_of_new_arr_copy[:] = 87
slice_of_new_arr_copy

array([87, 87, 87, 87, 87, 87, 87, 87, 87, 87])

In [59]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr_2d = np.array([[5,10,15],[20,25,30],[30,35,40]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [89]:
# в ответе первое число - кол-во строк, второе - кол-во столбцов
arr_2d.shape

(3, 3)

In [64]:
# получить первую строку двумерного массива (матрицы)
arr_2d[0]

array([ 5, 10, 15])

In [66]:
# получить тертью (последнюю) строку двумерного массива (матрицы)
arr_2d[2] 

array([30, 35, 40])

In [68]:
# получить второй элемент первой строки массива (матрицы)
arr_2d[0][1] # arr_2d[1,1]

10

In [70]:
# тоже самое что и выше
arr_2d[0,1]

10

In [71]:
# slices
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [72]:
# slices
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [78]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [83]:
bool_arr = arr >4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [86]:
# это фактически условие для фильтрации элементров массива по "элемент > 4"
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [88]:
# тоже что и выше
new_arr[arr > 4]

array([4, 5, 6, 7, 8, 9])