In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
mylist

[1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
# одномерный массив
myarr = np.array(mylist)
myarr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
type(myarr)

numpy.ndarray

In [8]:
# двумерный массив
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# верхняя граница np.arange не включается в вывод
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones (5)

array([1., 1., 1., 1., 1.])

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [17]:
len(np.linspace(0,10,11))

11

In [18]:
len(np.linspace(0,10,21))

21

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(1)

array([0.99748767])

In [21]:
np.random.rand(5,2)

array([[0.63701841, 0.16244208],
       [0.55707411, 0.82349155],
       [0.86569273, 0.76641312],
       [0.39827648, 0.94599394],
       [0.81796459, 0.08992753]])

In [22]:
# нормальное распределение (распределение Гаусса):
# Cтандартное нормальное распределение в котором математическое ожидание равно нулю, 
# а дисперcия равно 1
np.random.randn(10)

array([-1.30576845, -0.90646651, -0.42472385, -0.68647802,  0.70412092,
       -0.6606031 , -1.25325296,  1.18145649, -0.54539141, -0.08934157])

In [23]:
np.random.randn(2,3)

array([[-1.57690453,  1.16068378,  1.03376151],
       [-0.40801088, -0.16318508,  2.60142822]])

In [24]:
# целые случайные числа
np.random.randint(2, high=101, size=5)

array([ 2,  5, 65, 61, 79])

In [26]:
np.random.randint(2, high=101, size=(4, 5))

array([[60, 93, 93, 11, 23],
       [63, 21, 77, 68, 85],
       [41, 83, 19, 81, 55],
       [40, 59, 75, 70, 16]])

In [30]:
# воспроизводимый набор случайных числе с помощью seed
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
# просто полезный метод
arr = np.arange(0,25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
# мы не можем указать (5, 4) потому что не 25 значений из arr не поместятся в матрицу (5,4)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
ranarr = np.random.randint(0,101,10)

In [57]:
ranarr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [58]:
ranarr.max()

87

In [59]:
ranarr.min()

1

In [60]:
# позиция максимального значения
ranarr.argmax()

1

In [61]:
# позиция минимального значения
ranarr.argmin()

0

In [62]:
# атрибут .dtype позволяет посмотреть тип данных в массиве (целые или числа с плавающей точкой)
ranarr.dtype

dtype('int64')

In [63]:
# атрибут .shape показывает кол-=во элементов
arr.shape

(25,)

In [64]:
# создает матрицу из массива
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])