In [2]:
import numpy as np

In [3]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8]

In [5]:
type(mylist)

list

In [6]:
np.array(mylist)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
mylist

[1, 2, 3, 4, 5, 6, 7, 8]

In [9]:
# одномерный массив
myarr = np.array(mylist)
myarr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
type(myarr)

numpy.ndarray

In [11]:
# двумерный массив
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# верхняя граница np.arange не включается в вывод
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones (5)

array([1., 1., 1., 1., 1.])