In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../course_data/08-Linear-Regression-Models/Advertising.csv')
df.head()

,TV,radio,newspaper,sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9


In [3]:
# разбиваем данные на признаки и целевую переменную
X = df.drop('sales',axis=1)
y = df['sales']

In [4]:
from sklearn.preprocessing import PolynomialFeatures

In [5]:
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [6]:
poly_features = polynomial_converter.fit_transform(X)

In [7]:
poly_features.shape

(200, 19)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [10]:
X_train.shape

(140, 19)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()

In [13]:
scaler.fit(X_train)

StandardScaler()

In [14]:
X_train = scaler.transform(X_train)

In [15]:
X_test = scaler.transform(X_test)

In [16]:
X_train[20]

array([ 1.53148009, -0.6451493 ,  0.27531663,  1.91425237,  0.07916186,
        1.05173504, -0.79116567, -0.34072316, -0.0317756 ,  2.17746385,
        0.42192068,  1.34360044, -0.4468578 ,  0.06033585,  0.36735648,
       -0.76739309, -0.54548903, -0.33732268, -0.2041403 ])

In [17]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

### Ridge-регрессия (l2 regularization) - это метод регуляризацииб позволяющий снизить вероятность  переобученности модели (overfitting) на обучающем наборе данных (после кроссвалидации). Это достигается добавлемтем штрафующего слагаемого к ошибке, с квадратом значений коэффициентов



In [18]:
from sklearn.linear_model import Ridge

In [19]:
# help(Ridge)

In [20]:
ridge_model = Ridge(alpha=10)

In [21]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [22]:
test_prediction = ridge_model.predict(X_test)

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [24]:
MAE = mean_absolute_error(y_test, test_prediction)
MAE

0.5774404204714163

In [25]:
RMSE = np.sqrt(mean_squared_error(y_test, test_prediction))
RMSE

np.float64(0.894638646131965)

In [26]:
from sklearn.linear_model import RidgeCV

In [27]:
ridge_cv_model = RidgeCV(alphas=(0.1,1.0,10.0), scoring='neg_mean_absolute_percentage_error')

In [28]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(scoring='neg_mean_absolute_percentage_error')

In [29]:
ridge_cv_model.alpha_

np.float64(0.1)

In [30]:
from sklearn.metrics._scorer import _SCORERS

In [31]:
_SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'neg_max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_root_mean_squared_log_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'd2_absolute_error_score', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'positive_likelihood_ratio', 'neg_negative_likelihood_ratio', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'reca

In [32]:
test_prediction = ridge_cv_model.predict(X_test)

In [33]:
MAE = mean_absolute_error(y_test, test_prediction)
MAE

0.427377488434534

In [34]:
RMSE = np.sqrt(mean_squared_error(y_test, test_prediction))
RMSE

np.float64(0.6180719926938822)

In [35]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [36]:
ridge_cv_model.best_score_ 

-0.05223511190570337

### Lasso-регрессия (least absolute shringkage and selection operator).


In [61]:
from sklearn.linear_model import LassoCV

In [62]:
#LassoCV()

In [70]:
lasso_cv_model = LassoCV(eps=0.001,n_alphas=100,cv=5,max_iter=100000000)
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, max_iter=100000000)

In [71]:
lasso_cv_model.alpha_

np.float64(0.004943070909225831)

In [72]:
test_predictions = lasso_cv_model.predict(X_test)

In [73]:
MAE = mean_absolute_error(y_test, test_prediction)
MAE

0.427377488434534

In [74]:
RMSE = np.sqrt(mean_squared_error(y_test, test_prediction))
RMSE

np.float64(0.6180719926938822)

In [75]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])