### Полиномиальная регрессия
Возможные варианты улучшения линейной регрессии - добавить для признаков полиномы более высокой степени
Полиномиальная регрессия решает две задачи - моделирование нелинейной связи (когда все точки лежат не на прямой линии, а на какой-то прямой) и взаимодействие между отдельными признаками

### Создание обученной модели с полиномальной регрессией
Благодаря добавлению полинома создается больш признаков на которых будет проходить обучение модели для предстоящей линейной регрессии.
Новый набор признаков разбивается на тестовый и обучающий наборы 
fit() в Scikit-Learn необходим чтобы определиться с диапазоном значений данных, а затем transform() - для преобразования данных. fit_transform() - объединяем два этих метода.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../course_data/08-Linear-Regression-Models/Advertising.csv')
df.head()

,TV,radio,newspaper,sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9


In [3]:
X = df.drop('sales',axis=1)

In [4]:
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
polynomial_convert = PolynomialFeatures(degree=2,include_bias=False)

In [7]:
polynomial_convert.fit(X)

PolynomialFeatures(include_bias=False)

In [8]:
poly_features = polynomial_convert.transform(X)
poly_features

array([[ 230.1 ,   37.8 ,   69.2 , ..., 1428.84, 2615.76, 4788.64],
       [  44.5 ,   39.3 ,   45.1 , ..., 1544.49, 1772.43, 2034.01],
       [  17.2 ,   45.9 ,   69.3 , ..., 2106.81, 3180.87, 4802.49],
       ...,
       [ 177.  ,    9.3 ,    6.4 , ...,   86.49,   59.52,   40.96],
       [ 283.6 ,   42.  ,   66.2 , ..., 1764.  , 2780.4 , 4382.44],
       [ 232.1 ,    8.6 ,    8.7 , ...,   73.96,   74.82,   75.69]])

In [9]:
poly_features.shape

(200, 9)

In [10]:
X.shape

(200, 3)

In [11]:
X.iloc[0]

TV           230.1
radio         37.8
newspaper     69.2
Name: 0, dtype: float64

In [12]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

In [13]:
polynomial_convert.fit_transform(X)

array([[ 230.1 ,   37.8 ,   69.2 , ..., 1428.84, 2615.76, 4788.64],
       [  44.5 ,   39.3 ,   45.1 , ..., 1544.49, 1772.43, 2034.01],
       [  17.2 ,   45.9 ,   69.3 , ..., 2106.81, 3180.87, 4802.49],
       ...,
       [ 177.  ,    9.3 ,    6.4 , ...,   86.49,   59.52,   40.96],
       [ 283.6 ,   42.  ,   66.2 , ..., 1764.  , 2780.4 , 4382.44],
       [ 232.1 ,    8.6 ,    8.7 , ...,   73.96,   74.82,   75.69]])

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
## train_test_split -> нажимаем shift+tab -> копируем код из примера

In [16]:
poly_features.shape

(200, 9)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
model = LinearRegression()

In [20]:
model.fit(X_train, y_train)

LinearRegression()

In [21]:
test_predictions = model.predict(X_test)

In [22]:
model.coef_

array([ 5.17095811e-02,  1.30848864e-02,  1.20000085e-02, -1.10892474e-04,
        1.14212673e-03, -5.24100082e-05,  3.34919737e-05,  1.46380310e-04,
       -3.04715806e-05])

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [24]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.4896798044803838

In [25]:
MSE = mean_squared_error(y_test, test_predictions)
MSE

0.4417505510403753

In [26]:
RMSE = np.sqrt(MSE)
RMSE

np.float64(0.6646431757269274)

### Важно убедиться что разбиение на обучающий и тестовые наборы данных были выполнены одинаково для обеих моделей
... это гарантируется тем что указаны одинаковые параметры в test_size и random_state

### Вывод - полиномиальная регрессия работает заметно лучше, чем линейная

In [27]:
model.coef_

array([ 5.17095811e-02,  1.30848864e-02,  1.20000085e-02, -1.10892474e-04,
        1.14212673e-03, -5.24100082e-05,  3.34919737e-05,  1.46380310e-04,
       -3.04715806e-05])

In [28]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

In [ ]:
### Дулема смещения